---
- name: Add Conky-Manager PPA
  apt_repository:
    repo: 'ppa:teejee2008/ppa'
    state: present
  become: yes
  when: ansible_distribution != "Linuxmint"

- name: Add Conky-Manager PPA (Linuxmint Workaround)
  shell: add-apt-repository -y ppa:teejee2008/ppa
  become: true
  when: ansible_distribution == "Linuxmint"

- name: Install packages
  apt: 
    pkg: "{{ item }}"
    state: installed
    update_cache: yes
  with_items:
        - conky-all
        - conky-manager
        # Support packages
        - lm-sensors
        - hddtemp
        - dmidecode
  become: true

- block:

    - name: Remove default ConkyManager Settings
      file:
        path: "{{ conky_config_file }}"
        state: absent
      ignore_errors: yes
      when: conky_backup_restore

    - name: Symlink ConkyManager Settings
      file:
        src:  "{{ conky_backup_conky_manager_file }}"
        dest: "{{ conky_config_file }}"
        state: link
      when: conky_backup_symlink

    - name: Symlink Conky Dir
      file:
        src:  "{{ conky_backup_dir }}"
        dest: "/home/{{ os_username }}/.conky"
        state: link
      when: conky_backup_symlink

  when:
    - installed.changed
    - conky_backup_restore
    - conky_backup_conky_manager_file is defined
